### ISSUE TITLE
embed.su

### ISSUE THREAD

**Issue by Rhiannon99** [Toasty360/Junk#2]
i have this error on embed.su dart file if possible to fix it please Unhandled exception:
FormatException: Invalid encoding before padding (at character 135)
...YpN3MX5CMWZWaj5WU59WMaxWNHFWdsZkTLZFbRFzZz0ETORFVCJUMWBDcyEFNvZlYtxWRa5mV== 
                                                                            ^

**Comment by Toasty360** [comment]
I have noticed it too. I will check it later.
